import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";



export const metadata: Metadata = {
  title: "login page",
  description: "Generated by create next app",
};

export default function LoginLayout ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main >
   
        <ToastContainer />
        {children}
    </main>
  );
}
